/*
  Sample vaccination data
*/

const vaccinationData = [
  {
    id: "1",
    firstName: "Will",
    lastName: "Smith",
    patientId: "will.smith@ibm.com",
    dateOfBirth: "4/22/1990",
    gender: "Male",
    vaccine: "COVID19",
    provider: "Macquarie Hospital",
    request: "Pending",
    scheduledAppointment: null,
  },
  {
    id: "2",
    firstName: "Dwayne",
    lastName: "Johnson",
    patientId: "dwayne.johnson@ibm.com",
    dateOfBirth: "4/22/1990",
    gender: "Male",
    vaccine: "Smallpox",
    provider: "Hornsby Hospital",
    request: "Approved",
    scheduledAppointment: {
      date: "06/29/2021",
      time: "10:30",
      AMPM: "AM",
    },
  },
  {
    id: "3",
    firstName: "Keanu",
    lastName: "Reeves",
    patientId: "keanu.reeves@ibm.com",
    dateOfBirth: "4/23/1990",
    gender: "Male",
    vaccine: "Polio",
    provider: "Northwestern Memorial Hospital",
    request: "Approved",
    scheduledAppointment: {
      date: "07/11/2021",
      time: "12:30",
      AMPM: "PM",
    },
  },
  {
    id: "4",
    firstName: "Chris",
    lastName: "Stedman",
    patientId: "chris@ibm.com",
    dateOfBirth: "4/24/1990",
    gender: "Male",
    vaccine: "Yellow Fever",
    provider: "Chicago Lakeshore Hospital",
    request: "Pending",
    scheduledAppointment: null,
  },
  {
    id: "5",
    firstName: "Chris",
    lastName: "Evans",
    patientId: "chris.evans@ibm.com",
    dateOfBirth: "4/25/1990",
    gender: "Male",
    vaccine: "COVID19",
    provider: "Gardiner General Hospital",
    request: "Approved",
    scheduledAppointment: null,
  },
  {
    id: "6",
    firstName: "Nicole",
    lastName: "Kidman",
    patientId: "nicole.kidman@ibm.com",
    dateOfBirth: "1/1/2000",
    gender: "Female",
    vaccine: "COVID19",
    provider: "Gardiner General Hospital",
    request: "Approved",
    scheduledAppointment: {
      date: "07/22/2021",
      time: "02:30",
      AMPM: "PM",
    },
  },
  {
    id: "7",
    firstName: "Will",
    lastName: "Smith",
    patientId: "will.smith@ibm.com",
    dateOfBirth: "4/22/1990",
    gender: "Male",
    vaccine: "COVID19",
    provider: "Macquarie Hospital",
    request: "Pending",
    scheduledAppointment: null,
  },
  {
    id: "8",
    firstName: "Dwayne",
    lastName: "Johnson",
    patientId: "dwayne.johnson@ibm.com",
    dateOfBirth: "4/22/1990",
    gender: "Male",
    vaccine: "COVID19",
    provider: "Hornsby Hospital",
    request: "Pending",
    scheduledAppointment: null,
  },
  {
    id: "9",
    firstName: "Keanu",
    lastName: "Reeves",
    patientId: "keanu.reeves@ibm.com",
    dateOfBirth: "4/23/1990",
    gender: "Male",
    vaccine: "Smallpox",
    provider: "Northwestern Memorial Hospital",
    request: "Approved",
    scheduledAppointment: null,
  },
  {
    id: "10",
    firstName: "Chris",
    lastName: "Stedman",
    patientId: "chris@ibm.com",
    dateOfBirth: "4/24/1990",
    gender: "Male",
    vaccine: "Polio",
    provider: "Chicago Lakeshore Hospital",
    request: "Approved",
    scheduledAppointment: {
      date: "06/30/2021",
      time: "11:30",
      AMPM: "AM",
    },
  },
  {
    id: "11",
    firstName: "Chris",
    lastName: "Evans",
    patientId: "chris.evans@ibm.com",
    dateOfBirth: "4/25/1990",
    gender: "Male",
    vaccine: "Yellow Fever",
    provider: "Gardiner General Hospital",
    request: "Pending",
    scheduledAppointment: null,
  },
  {
    id: "12",
    firstName: "Nicole",
    lastName: "Kidman",
    patientId: "nicole.kidman@ibm.com",
    dateOfBirth: "1/1/2000",
    gender: "Male",
    vaccine: "Smallpox",
    provider: "Gardiner General Hospital",
    request: "Approved",
    scheduledAppointment: null,
  },
];

export default vaccinationData;
